### ISSUE TITLE
Write test for class ConfirmationBlockHistory to cover creation of block history

### ISSUE THREAD

**Issue by pgeorge2** [thenewboston-developers/Validator#108]
Write a test called `test_confirmation_block_history_post` to create a connection request and verify the status code 201 for successful record creation.

Hint: prepare a test using url `confirmation_block_history and pass dummy data using Factory method and verify the response and 200 status. Consider `ConfirmationBlockHistorySerializer` serializer for reference.

**Comment by Sulaiman001** [comment]
Hi @pgeorge2 , please share your account number so that we know where to send your coins. Every accepted PR gets paid. If you do not yet have an account then please download the account manager here https://thenewboston.com/download and follow these steps https://thenewboston.com/account-manager/create-an-account to create an account.

**Comment by vosi** [comment]
@Sulaiman001 Pgeorge2 is not the person that should be paid, the person who completed the task is @DucPhamTV

**Comment by Sulaiman001** [comment]
Okay thank you for the correction
